{"name": "test_login[standard_user-2452]", "status": "failed", "statusDetails": {"message": "AssertionError: Invalid credentials\nassert 'Epic sadface... this service' == ''\n  \n  + Epic sadface: Username and password do not match any user in this service", "trace": "username = 'standard_user', password = '2452'\n\n    @pytest.mark.login\n    @pytest.mark.parametrize(\"username, password\", get_data())\n    def test_login(username, password):\n        driver = SeleniumWebDriver(implicitly_wait=1, explicitly_wait=1)\n        page = SauceDemoPage(driver)\n        msg = page.Login(username, password)\n        driver.close(exit_time=2)\n>       assert msg == '', 'Invalid credentials'\nE       AssertionError: Invalid credentials\nE       assert 'Epic sadface... this service' == ''\nE         \nE         + Epic sadface: Username and password do not match any user in this service\n\nreports\\test_02_pytest_allure.py:25: AssertionError"}, "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'2452'"}], "start": 1707771400106, "stop": 1707771405196, "uuid": "42dff9cf-5b41-4a1f-a0c6-7e73da540cd0", "historyId": "ee921040763b31aec8924dd88139b11e", "testCaseId": "e30dcb273174ee6b93f1c89a0eff4e28", "fullName": "reports.test_02_pytest_allure#test_login", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "reports"}, {"name": "suite", "value": "test_02_pytest_allure"}, {"name": "host", "value": "DESKTOP-551JSCE"}, {"name": "thread", "value": "58820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "reports.test_02_pytest_allure"}]}